### get list of projects
http://localhost:8080/project

### get a project (default demo project)
http://localhost:8080/project/abc123

### create a project
POST http://localhost:8080/project
content-type: application/json

{
    "name": "Super Game 1",
    "description": "Awesome description"
}

### update the demo project
PUT http://localhost:8080/project/abc123
content-type: application/json

{
    "name": "Update name",
    "description": "Updateds description"
}

# upload zip file a project
# POST http://localhost:8080/project/upload